on:
  pull_request:
  push:
    branches:
    - main

name: build
jobs:

  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            libapparmor: true
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - if: ${{ matrix.libapparmor }}
      name: Install libapparmor-dev
      run: sudo apt-get install -y libapparmor-dev
    - name: Build
      run: make build
    - name: Tests
      run: make test
    - if: ${{ matrix.libapparmor }}
      name: E2E Tests
      run: make e2e
