on:
  pull_request:
  push:
    branches:
    - main

name: build
jobs:

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install libapparmor-dev
      run: sudo apt-get install -y libapparmor-dev
    - name: Build
      run: |
        make build
    - name: Build Example Code
      run: |
        make example

  macos:
    runs-on: macos-latest
    env:
      BUILD_TAGS: "netgo"
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        make build
    - name: Build Example Code
      run: |
        make example
